### PR TITLE
Completed Review Section Functionality 

### PR DESCRIPTION
**Pull request by gordon1213**
@LukeLarson2  Needed to add an id tag to your container so that I could reference it in my anchor tag.

### CODE REVIEW

**Review by LukeLarson2 — CHANGES_REQUESTED** [review]
In the situation of wanting to scroll to an element in the form you would actually want to use the react hook useRef(). Without getting into the details here, this is an article on how to implement a smooth scroll feature to an element in the DOM

https://www.codingbeautydev.com/blog/react-scroll-to-element

**Comment by gordon1213** [comment]
Made changes so that it uses uses scrollintoView() and useRef

**Review by clee4037 — APPROVED** [review]
Looks good!

**Review by LukeLarson2 — APPROVED** [review]
good to go thank you for making changes

**Pull request merged**
