### PR TITLE
Ro card layout

### PR DESCRIPTION
**Pull request by clee4037**
@gordon1213 @kssampson Please review!

### CODE REVIEW

**Review by gordon1213 — COMMENTED** [review]
If we aren't labelling our css files by initials anymore it looks fine to me

**Review by LukeLarson2 — CHANGES_REQUESTED** [review]
Please go back through and add the appropriate naming conventions for classNames to have the appropriate letter prefix c- to avoid potential styling conflicts

**Comment by clee4037** [comment]
@LukeLarson2 updated classnames please review

**Review by LukeLarson2 — APPROVED** [review]
Thank you for making corrections, looks great!

**Pull request merged**
